/* Package catalogue.
   Each package: id, state, title, days, price, mrp (optional, shows % off),
   themes, scene (illustration used when no photo), img (optional photo),
   arrive (pickup point), route, highlights, itinerary [[title, text], ...],
   inc / exc / prep (extra lines added to the defaults in catalog.js), tm (tour manager).
   To use a real photo, save it as images/pkg/<id>.jpg — it replaces the illustration. */
window.STATES = [
  {id: 'tn', name: 'Tamil Nadu', scene: 'temple', img: 'images/chola-trail.jpg'},
  {id: 'kl', name: 'Kerala', scene: 'hills', img: 'images/kerala-backwaters.jpg'},
  {id: 'an', name: 'Andaman', scene: 'beach', img: 'images/andaman-coral.jpg'},
  {id: 'sk', name: 'Sikkim & Darjeeling', scene: 'monastery', img: 'images/sikkimdarjlind.jpg'},
  {id: 'hp', name: 'Himachal & Spiti', scene: 'snow', img: 'images/himachalandspiti.jpg'},
  {id: 'jk', name: 'Jammu & Kashmir', scene: 'lake', img: 'images/jammukashmir.jpg'},
  {id: 'la', name: 'Leh Ladakh', scene: 'ladakh', img: 'images/lehladakh.jpg'},
  {id: 'rj', name: 'Rajasthan', scene: 'desert', img: 'images/rajasthan.jpg'},
  {id: 'uk', name: 'Uttarakhand', scene: 'river', img: 'images/uttarakhand.png'},
  {id: 'dl', name: 'Delhi & Agra', scene: 'city', img: 'images/delhiagra.jpg'},
  {id: 'bt', name: 'Bhutan', scene: 'monastery', img: 'images/bhutan.jpg'},
  {id: 'th', name: 'Thailand', scene: 'pagoda', img: 'images/thailand.jpg'}
];

/* Theme photos: save them as images/themes/<file> below. Until a file exists the illustration shows. */
window.THEMES = [
  {id: 'Honeymoon', scene: 'beach', img: 'images/themes/honeymoon.jpg'},
  {id: 'Friends/Group', scene: 'snow', img: 'images/themes/friends-group.jpg'},
  {id: 'Adventure', scene: 'ladakh', img: 'images/themes/adventure.jpg'},
  {id: 'Nature', scene: 'hills', img: 'images/themes/nature.jpg'},
  {id: 'Solo', scene: 'monastery', img: 'images/themes/solo.jpg'},
  {id: 'Family', scene: 'palace', img: 'images/themes/family.jpg'}
];

window.PACKAGES = [
  /* ---------- Tamil Nadu ---------- */
  {id: 'chola-trail', state: 'tn', title: 'The Chola Trail', days: 5, price: 48500, signature: true,
    themes: ['Family', 'Solo'], scene: 'temple', img: 'images/chola-trail.jpg', tm: true,
    arrive: 'Chennai Airport', route: 'Chennai → Mahabalipuram → Thanjavur',
    highlights: ['Sunset at the Shore Temple, Mahabalipuram', 'Arjuna\'s Penance and the Five Rathas', 'Brihadisvara Temple at dusk with a historian guide', 'Private Bharatanatyam recital', 'Chauffeur-driven car for the whole trip'],
    itinerary: [
      ['Arrive Chennai, drive to Mahabalipuram', 'Pickup at Chennai Airport and drive down the East Coast Road. Evening at the Shore Temple.'],
      ['Mahabalipuram monuments', 'Arjuna\'s Penance, the Five Rathas and Krishna\'s Butter Ball with your guide.'],
      ['Drive to Thanjavur', 'Drive inland to Thanjavur. Evening visit to the Brihadisvara Temple.'],
      ['Thanjavur and recital', 'Thanjavur Palace and art gallery. Private Bharatanatyam recital in the evening.'],
      ['Departure', 'Drive to Trichy Airport or back to Chennai for your onward journey.']]},
  {id: 'chettinad', state: 'tn', title: 'Chettinad Mansions', days: 4, price: 42000, signature: true,
    themes: ['Family', 'Solo'], scene: 'palace', img: 'images/chettinad-mansions.jpg',
    arrive: 'Madurai Airport', route: 'Madurai → Karaikudi → Athangudi',
    highlights: ['Stay in a restored Chettinad mansion', 'Cooking session with a Chettiar family', 'Athangudi handmade tile workshop', 'Antique market in Karaikudi'],
    itinerary: [
      ['Arrive Madurai, drive to Karaikudi', 'Pickup at Madurai Airport. Check in to your heritage mansion.'],
      ['Mansions and tiles', 'Walk through the mansion lanes and visit an Athangudi tile workshop.'],
      ['Cooking and antiques', 'Cook a Chettinad lunch with a local family. Evening at the antique market.'],
      ['Departure', 'Drive back to Madurai Airport.']]},
  {id: 'tn-ooty-kodai', state: 'tn', title: 'Ooty & Kodaikanal Hill Station Tour', days: 6, price: 18999, mrp: 22999,
    themes: ['Family', 'Honeymoon', 'Nature'], scene: 'hills', img: 'images/munnar-tea-hills.jpg',
    arrive: 'Coimbatore Airport / Railway Station', route: 'Coimbatore → Ooty → Kodaikanal → Madurai',
    highlights: ['Nilgiri Mountain Railway toy train ride', 'Doddabetta Peak viewpoint', 'Boating on Ooty Lake and Kodaikanal Lake', 'Coaker\'s Walk and Pillar Rocks', 'Tea estates of Coonoor'],
    itinerary: [
      ['Coimbatore to Ooty', 'Pickup and drive up the ghat road to Ooty. Evening free at the market.'],
      ['Ooty sightseeing', 'Botanical Garden, Ooty Lake boating and Doddabetta Peak.'],
      ['Coonoor and toy train', 'Toy train ride on the Nilgiri Mountain Railway (subject to tickets), Sim\'s Park and Dolphin\'s Nose.'],
      ['Ooty to Kodaikanal', 'Long scenic drive to Kodaikanal. Evening at the lake.'],
      ['Kodaikanal sightseeing', 'Coaker\'s Walk, Pillar Rocks, Bryant Park and Kodaikanal Lake boating.'],
      ['Departure from Madurai', 'Drive down to Madurai for your onward train or flight.']]},
  {id: 'tn-temple-trail', state: 'tn', title: 'Madurai, Rameswaram & Kanyakumari Tour', days: 5, price: 15499,
    themes: ['Family', 'Solo'], scene: 'temple', img: 'images/bharatanatyam-heritage.jpg',
    arrive: 'Madurai Airport / Railway Station', route: 'Madurai → Rameswaram → Kanyakumari',
    highlights: ['Meenakshi Amman Temple, Madurai', 'Ramanathaswamy Temple corridors', 'Pamban Bridge and Dhanushkodi', 'Vivekananda Rock Memorial', 'Sunset at the tip of India'],
    itinerary: [
      ['Arrive Madurai', 'Meenakshi Amman Temple and Thirumalai Nayakkar Mahal.'],
      ['Madurai to Rameswaram', 'Drive across the Pamban Bridge. Evening at Ramanathaswamy Temple.'],
      ['Dhanushkodi', 'Morning drive to Dhanushkodi and the APJ Abdul Kalam Memorial. Drive to Kanyakumari.'],
      ['Kanyakumari', 'Sunrise, ferry to the Vivekananda Rock Memorial and Thiruvalluvar Statue. Sunset at the beach.'],
      ['Departure', 'Drive to Trivandrum or Madurai for your onward journey.']]},
  {id: 'tn-pondy', state: 'tn', title: 'Pondicherry Weekend Getaway', days: 3, price: 8999, mrp: 10999,
    themes: ['Friends/Group', 'Honeymoon', 'Solo'], scene: 'beach', img: 'images/chola-trail.jpg',
    arrive: 'Chennai', route: 'Chennai → Mahabalipuram → Pondicherry',
    highlights: ['French Quarter heritage walk', 'Promenade Beach at sunrise', 'Auroville and the Matrimandir viewpoint', 'Paradise Beach boat ride', 'Stop at Mahabalipuram on the way'],
    itinerary: [
      ['Chennai to Pondicherry', 'Pickup in Chennai, stop at Mahabalipuram, reach Pondicherry by evening.'],
      ['Pondicherry sightseeing', 'French Quarter, Sri Aurobindo Ashram, Auroville and Promenade Beach.'],
      ['Paradise Beach and return', 'Morning boat to Paradise Beach, then drive back to Chennai.']]},

  /* ---------- Kerala ---------- */
  {id: 'kerala-backwaters', state: 'kl', title: 'Kerala Backwaters', days: 6, price: 62000, signature: true,
    themes: ['Honeymoon', 'Family'], scene: 'hills', img: 'images/kerala-backwaters.jpg',
    arrive: 'Cochin Airport', route: 'Cochin → Munnar → Alleppey',
    highlights: ['Private houseboat with an onboard chef', 'Ayurvedic therapy session', 'Tea estate stay in Munnar', 'Fort Kochi and the Chinese fishing nets'],
    itinerary: [
      ['Arrive Cochin', 'Fort Kochi, Chinese fishing nets and Mattancherry.'],
      ['Cochin to Munnar', 'Drive into the tea hills. Check in to your tea estate bungalow.'],
      ['Munnar', 'Eravikulam National Park, Mattupetty Dam and the Tea Museum.'],
      ['Ayurveda day', 'Morning Ayurvedic therapy, afternoon walk through the estate.'],
      ['Houseboat on the backwaters', 'Board your private houseboat at Alleppey. Lunch and dinner cooked onboard.'],
      ['Departure', 'Disembark and drive to Cochin Airport.']],
    inc: ['Private houseboat with all meals onboard', 'One Ayurvedic therapy session']},
  {id: 'kl-munnar-alleppey', state: 'kl', title: 'Munnar & Alleppey Tour Package', days: 5, price: 16999, mrp: 20999,
    themes: ['Family', 'Nature', 'Honeymoon'], scene: 'hills', img: 'images/munnar-tea-hills.jpg',
    arrive: 'Cochin Airport / Ernakulam Station', route: 'Cochin → Munnar → Thekkady → Alleppey',
    highlights: ['Tea gardens and Eravikulam National Park', 'Periyar Lake boat ride, Thekkady', 'Spice plantation walk', 'Overnight houseboat in Alleppey'],
    itinerary: [
      ['Cochin to Munnar', 'Waterfalls and spice gardens on the drive up to Munnar.'],
      ['Munnar sightseeing', 'Eravikulam National Park, Mattupetty Dam, Echo Point and the Tea Museum.'],
      ['Munnar to Thekkady', 'Spice plantation tour and an evening Kathakali or Kalaripayattu show.'],
      ['Thekkady to Alleppey', 'Morning boat ride on Periyar Lake, then board the houseboat in Alleppey.'],
      ['Departure', 'Check out from the houseboat and drive to Cochin.']],
    inc: ['One night on a shared-category houseboat with meals']},
  {id: 'kl-honeymoon', state: 'kl', title: 'Kerala Honeymoon with Kovalam Beach', days: 7, price: 24999, mrp: 29999,
    themes: ['Honeymoon'], scene: 'beach', img: 'images/themes/honeymoon.jpg',
    arrive: 'Cochin Airport', route: 'Cochin → Munnar → Thekkady → Alleppey → Kovalam',
    highlights: ['Candle-light dinner in Munnar', 'Private houseboat night', 'Kovalam lighthouse beach', 'Flower bed decoration on arrival'],
    itinerary: [
      ['Arrive Cochin, drive to Munnar', 'Scenic drive to Munnar. Room decorated for your arrival.'],
      ['Munnar', 'Tea gardens, Top Station and a candle-light dinner.'],
      ['Thekkady', 'Spice plantation and Periyar Lake.'],
      ['Alleppey houseboat', 'Private houseboat through the backwaters with meals onboard.'],
      ['Kovalam', 'Drive to Kovalam. Evening at Lighthouse Beach.'],
      ['Trivandrum', 'Padmanabhaswamy Temple (outside view for non-Hindus) and a free beach afternoon.'],
      ['Departure', 'Drop at Trivandrum Airport.']],
    inc: ['Private houseboat night with meals', 'One candle-light dinner', 'Honeymoon room decoration']},
  {id: 'kl-short', state: 'kl', title: 'Kochi & Munnar Short Break', days: 4, price: 12999,
    themes: ['Family', 'Nature', 'Solo'], scene: 'hills', img: 'images/munnar-tea-hills.jpg',
    arrive: 'Cochin Airport', route: 'Cochin → Munnar → Cochin',
    highlights: ['Fort Kochi heritage walk', 'Two nights in the tea hills', 'Cheeyappara and Valara waterfalls'],
    itinerary: [
      ['Arrive Cochin', 'Fort Kochi, Jew Town and the Chinese fishing nets.'],
      ['Cochin to Munnar', 'Waterfall stops on the way to Munnar.'],
      ['Munnar sightseeing', 'Eravikulam National Park, Mattupetty Dam and Echo Point.'],
      ['Departure', 'Drive back to Cochin.']]},

  /* ---------- Andaman ---------- */
  {id: 'andaman-coral', state: 'an', title: 'Andaman Coral', days: 7, price: 95000, signature: true,
    themes: ['Honeymoon', 'Adventure'], scene: 'beach', img: 'images/andaman-coral.jpg',
    arrive: 'Port Blair Airport', route: 'Port Blair → Havelock Island',
    highlights: ['Private catamaran day', 'Reef dives with a dive master', 'Beachfront suite near Radhanagar Beach', 'Cellular Jail light and sound show'],
    itinerary: [
      ['Arrive Port Blair', 'Cellular Jail and the evening light and sound show.'],
      ['Ferry to Havelock', 'Morning ferry to Swaraj Dweep (Havelock). Sunset at Radhanagar Beach.'],
      ['Catamaran day', 'Private catamaran sail with snorkelling stops.'],
      ['Reef dive', 'Guided dive with a certified dive master.'],
      ['Elephant Beach', 'Snorkelling and a free afternoon.'],
      ['Back to Port Blair', 'Ferry back. Evening at Corbyn\'s Cove.'],
      ['Departure', 'Drop at Port Blair Airport.']],
    inc: ['Private catamaran day', 'One guided dive with equipment']},
  {id: 'an-islands', state: 'an', title: 'Andaman 4 Nights 5 Days Island Tour', days: 5, price: 21999, mrp: 25999,
    themes: ['Family', 'Honeymoon', 'Friends/Group'], scene: 'beach', img: 'images/andaman-coral.jpg',
    arrive: 'Port Blair Airport', route: 'Port Blair → Havelock → Neil Island',
    highlights: ['Cellular Jail light and sound show', 'Radhanagar Beach, Havelock', 'Natural Bridge, Neil Island', 'Laxmanpur Beach sunset', 'Inter-island ferries included'],
    itinerary: [
      ['Arrive Port Blair', 'Cellular Jail and the light and sound show.'],
      ['Port Blair to Havelock', 'Ferry to Havelock. Afternoon at Radhanagar Beach.'],
      ['Havelock to Neil', 'Morning at Elephant Beach (activities extra), ferry to Neil Island. Sunset at Laxmanpur Beach.'],
      ['Neil to Port Blair', 'Bharatpur Beach and the Natural Bridge, ferry back to Port Blair.'],
      ['Departure', 'Drop at Port Blair Airport.']],
    inc: ['Ferry tickets Port Blair – Havelock – Neil – Port Blair']},
  {id: 'an-honeymoon', state: 'an', title: 'Andaman Honeymoon Special', days: 6, price: 27999, mrp: 33999,
    themes: ['Honeymoon'], scene: 'beach', img: 'images/andaman-coral.jpg',
    arrive: 'Port Blair Airport', route: 'Port Blair → Havelock → Neil → Port Blair',
    highlights: ['Beach-facing room in Havelock', 'Candle-light dinner on the beach', 'Ross Island (Netaji Subhas Chandra Bose Dweep)', 'Glass-bottom boat at North Bay'],
    itinerary: [
      ['Arrive Port Blair', 'Cellular Jail and Corbyn\'s Cove.'],
      ['Ross Island and North Bay', 'Boat to Ross Island and North Bay with a glass-bottom boat ride.'],
      ['Ferry to Havelock', 'Check in to a beach-facing room. Candle-light dinner.'],
      ['Havelock', 'Radhanagar Beach and Kalapathar Beach.'],
      ['Neil Island', 'Day at Neil Island, ferry back to Port Blair.'],
      ['Departure', 'Drop at Port Blair Airport.']],
    inc: ['One candle-light dinner', 'Glass-bottom boat ride at North Bay']},

  /* ---------- Sikkim & Darjeeling ---------- */
  {id: 'sk-north', state: 'sk', title: 'Gangtok 5 Days with North Sikkim (Lachung)', days: 5, price: 15999, mrp: 18999,
    themes: ['Family', 'Friends/Group', 'Nature'], scene: 'snow', img: 'images/sikkimdarjlind.jpg',
    arrive: 'Bagdogra Airport / NJP Railway Station', route: 'Bagdogra → Gangtok → Lachung → Gangtok',
    highlights: ['Yumthang Valley in North Sikkim', 'Zero Point (weather permitting)', 'Tsomgo Lake and Baba Mandir', 'MG Marg evening walk', 'Permits arranged by us'],
    itinerary: [
      ['Bagdogra to Gangtok', 'Pickup and drive along the Teesta to Gangtok. Evening at MG Marg.'],
      ['Gangtok to Lachung', 'Drive north past waterfalls to Lachung.'],
      ['Yumthang Valley', 'Yumthang Valley and Zero Point (weather permitting), return to Gangtok.'],
      ['Tsomgo Lake', 'Day trip to Tsomgo Lake and Baba Mandir.'],
      ['Departure', 'Drive back to Bagdogra or NJP.']],
    prep: ['Carry 4 passport-size photos and ID copies for North Sikkim permits.']},
  {id: 'sk-nathula', state: 'sk', title: 'Gangtok 4 Days with Nathula Pass & City Tour', days: 4, price: 9999,
    themes: ['Family', 'Friends/Group', 'Solo'], scene: 'snow', img: 'images/sikkimdarjlind.jpg',
    arrive: 'Bagdogra Airport / NJP Railway Station', route: 'Bagdogra → Gangtok',
    highlights: ['Nathula Pass on the India–China border (permit based)', 'Tsomgo Lake', 'Rumtek Monastery', 'Banjhakri Falls and Ganesh Tok'],
    itinerary: [
      ['Bagdogra to Gangtok', 'Pickup and drive to Gangtok.'],
      ['Tsomgo Lake and Nathula', 'Tsomgo Lake, Baba Mandir and Nathula Pass (subject to permit).'],
      ['Gangtok city tour', 'Rumtek Monastery, Banjhakri Falls, Ganesh Tok and Tashi Viewpoint.'],
      ['Departure', 'Drive back to Bagdogra or NJP.']],
    prep: ['Nathula permits are issued to Indian nationals only. Carry photo ID and passport-size photos.']},
  {id: 'sk-pelling', state: 'sk', title: 'Gangtok & Pelling Tour Package', days: 6, price: 18999,
    themes: ['Nature', 'Family', 'Solo'], scene: 'monastery', img: 'images/sikkimdarjlind.jpg',
    arrive: 'Bagdogra Airport / NJP Railway Station', route: 'Bagdogra → Gangtok → Pelling',
    highlights: ['Kanchenjunga views from Pelling', 'Pemayangtse Monastery and Rabdentse Ruins', 'Pelling Skywalk', 'Khecheopalri Lake'],
    itinerary: [
      ['Bagdogra to Gangtok', 'Pickup and drive to Gangtok.'],
      ['Gangtok', 'Tsomgo Lake and Baba Mandir.'],
      ['Gangtok city', 'Rumtek Monastery and Banjhakri Falls.'],
      ['Gangtok to Pelling', 'Drive west to Pelling. Evening view of the Kanchenjunga range.'],
      ['Pelling', 'Pemayangtse Monastery, Rabdentse Ruins, the Skywalk and Khecheopalri Lake.'],
      ['Departure', 'Drive to Bagdogra or NJP.']]},
  {id: 'sk-darjeeling', state: 'sk', title: 'Darjeeling 3 Days Tea & Toy Train Tour', days: 3, price: 8499,
    themes: ['Family', 'Honeymoon', 'Nature'], scene: 'hills', img: 'images/sikkimdarjlind.jpg',
    arrive: 'Bagdogra Airport / NJP Railway Station', route: 'Bagdogra → Darjeeling',
    highlights: ['Tiger Hill sunrise over Kanchenjunga', 'Batasia Loop and Ghoom Monastery', 'Darjeeling Himalayan Railway joy ride', 'Tea garden visit'],
    itinerary: [
      ['Bagdogra to Darjeeling', 'Pickup and drive up to Darjeeling. Evening at the Mall.'],
      ['Darjeeling sightseeing', 'Tiger Hill sunrise, Batasia Loop, Ghoom Monastery, the Himalayan Mountaineering Institute and a tea garden.'],
      ['Toy train and departure', 'Joy ride on the toy train (subject to tickets), then drive to Bagdogra.']]},
  {id: 'sk-combo', state: 'sk', title: 'Darjeeling, Gangtok & Kalimpong Tour', days: 7, price: 22999, mrp: 26999,
    themes: ['Family', 'Friends/Group'], scene: 'monastery', img: 'images/sikkimdarjlind.jpg',
    arrive: 'Bagdogra Airport / NJP Railway Station', route: 'Bagdogra → Darjeeling → Kalimpong → Gangtok',
    highlights: ['Tiger Hill sunrise', 'Kalimpong monasteries and flower nurseries', 'Tsomgo Lake', 'MG Marg, Gangtok'],
    itinerary: [
      ['Bagdogra to Darjeeling', 'Drive up to Darjeeling.'],
      ['Darjeeling', 'Tiger Hill, Batasia Loop and Ghoom Monastery.'],
      ['Darjeeling to Kalimpong', 'Durpin Monastery and a flower nursery.'],
      ['Kalimpong to Gangtok', 'Drive to Gangtok. Evening at MG Marg.'],
      ['Tsomgo Lake', 'Tsomgo Lake and Baba Mandir.'],
      ['Gangtok city', 'Rumtek Monastery and Ganesh Tok.'],
      ['Departure', 'Drive to Bagdogra or NJP.']]},

  /* ---------- Himachal & Spiti ---------- */
  {id: 'hp-shimla-manali', state: 'hp', title: 'Shimla Manali 6 Days Tour Package', days: 6, price: 17999, mrp: 21999,
    themes: ['Family', 'Honeymoon', 'Friends/Group'], scene: 'snow', img: 'images/himachalandspiti.jpg',
    arrive: 'Chandigarh / Delhi', route: 'Chandigarh → Shimla → Manali',
    highlights: ['Mall Road and the Ridge, Shimla', 'Kufri snow point', 'Solang Valley', 'Atal Tunnel to Sissu', 'Hadimba Temple and Old Manali'],
    itinerary: [
      ['Chandigarh to Shimla', 'Pickup and drive to Shimla. Evening on Mall Road and the Ridge.'],
      ['Kufri', 'Day trip to Kufri. Christ Church and Jakhu Temple.'],
      ['Shimla to Manali', 'Drive via Kullu with a stop on the Beas. Rafting optional.'],
      ['Solang and Atal Tunnel', 'Solang Valley and a drive through the Atal Tunnel to Sissu.'],
      ['Manali', 'Hadimba Temple, Vashisht hot springs and Old Manali cafés.'],
      ['Departure', 'Drive back to Chandigarh.']]},
  {id: 'hp-volvo', state: 'hp', title: 'Manali 4 Nights 5 Days from Delhi by Volvo', days: 5, price: 7500,
    themes: ['Friends/Group', 'Solo'], scene: 'snow', img: 'images/himachalandspiti.jpg',
    arrive: 'Delhi (Volvo boarding point)', route: 'Delhi → Manali → Delhi (overnight Volvo)',
    highlights: ['Overnight AC Volvo both ways', 'Solang Valley', 'Hadimba Temple', 'Mall Road, Manali'],
    itinerary: [
      ['Delhi overnight Volvo', 'Board the evening Volvo from Delhi.'],
      ['Arrive Manali', 'Check in and rest. Evening on Mall Road.'],
      ['Solang Valley', 'Solang Valley and Atal Tunnel (vehicle charges extra).'],
      ['Manali local', 'Hadimba Temple, Vashisht and Club House. Board the evening Volvo.'],
      ['Arrive Delhi', 'Morning arrival in Delhi.']],
    inc: ['AC Volvo seats Delhi – Manali – Delhi']},
  {id: 'hp-dharamshala', state: 'hp', title: 'Dharamshala & Dalhousie 5 Days from Chandigarh', days: 5, price: 12400,
    themes: ['Family', 'Nature', 'Solo'], scene: 'monastery', img: 'images/himachalandspiti.jpg',
    arrive: 'Chandigarh', route: 'Chandigarh → Dharamshala → Dalhousie',
    highlights: ['McLeod Ganj and the Dalai Lama Temple', 'Bhagsu Nag waterfall', 'Khajjiar meadow', 'HPCA cricket stadium'],
    itinerary: [
      ['Chandigarh to Dharamshala', 'Pickup and drive to Dharamshala.'],
      ['McLeod Ganj', 'Dalai Lama Temple complex, Bhagsu Nag waterfall and the HPCA stadium.'],
      ['Dharamshala to Dalhousie', 'Drive to Dalhousie. Evening at Gandhi Chowk.'],
      ['Khajjiar', 'Day trip to the Khajjiar meadow and lake.'],
      ['Departure', 'Drive back to Chandigarh or Pathankot.']]},
  {id: 'hp-spiti', state: 'hp', title: 'Spiti Valley 8 Days: Shimla to Manali', days: 8, price: 27500,
    themes: ['Adventure', 'Friends/Group', 'Solo'], scene: 'ladakh', tm: true, img: 'images/himachalandspiti.jpg',
    arrive: 'Shimla', route: 'Shimla → Kalpa → Nako → Kaza → Chandratal → Manali',
    highlights: ['Full Spiti circuit by road', 'Key Monastery and Kibber village', 'Chandratal Lake', 'Kunzum Pass', 'Tabo and Nako'],
    itinerary: [
      ['Shimla to Sarahan', 'Drive along the Sutlej to Sarahan.'],
      ['Sarahan to Kalpa', 'Kinnaur valley views of the Kinner Kailash range.'],
      ['Kalpa to Nako', 'Nako lake and village.'],
      ['Nako to Kaza via Tabo', 'Tabo Monastery on the way to Kaza.'],
      ['Kaza', 'Key Monastery, Kibber and Langza.'],
      ['Kaza to Chandratal', 'Cross Kunzum Pass to the Chandratal camps.'],
      ['Chandratal to Manali', 'Drive out via the Atal Tunnel to Manali.'],
      ['Departure', 'Drop at Manali bus stand.']],
    prep: ['The Kunzum Pass road usually opens only in summer. We confirm road status before you travel.', 'Spend your first day resting to adjust to altitude.']},
  {id: 'hp-chandratal', state: 'hp', title: '4 Days Spiti from Manali via Atal Tunnel & Chandratal', days: 4, price: 15990,
    themes: ['Adventure', 'Solo'], scene: 'ladakh', img: 'images/himachalandspiti.jpg',
    arrive: 'Manali', route: 'Manali → Chandratal → Kaza → Manali',
    highlights: ['Atal Tunnel', 'Night in a Chandratal camp', 'Key Monastery', 'Kunzum Pass'],
    itinerary: [
      ['Manali to Chandratal', 'Through the Atal Tunnel and over Kunzum Pass to the Chandratal camps.'],
      ['Chandratal to Kaza', 'Morning at the lake, drive to Kaza.'],
      ['Kaza', 'Key Monastery and Kibber.'],
      ['Kaza to Manali', 'Drive back to Manali.']],
    prep: ['The Kunzum Pass road usually opens only in summer. We confirm road status before you travel.']},

  /* ---------- Jammu & Kashmir ---------- */
  {id: 'jk-srinagar', state: 'jk', title: 'Srinagar 5 Nights 6 Days – Sonmarg, Gulmarg & Pahalgam', days: 6, price: 16000, mrp: 19999,
    themes: ['Family', 'Honeymoon', 'Friends/Group'], scene: 'lake', img: 'images/jammukashmir.jpg',
    arrive: 'Srinagar Airport', route: 'Srinagar → Sonmarg → Gulmarg → Pahalgam',
    highlights: ['Shikara ride on Dal Lake', 'Night on a houseboat', 'Gulmarg Gondola', 'Betaab Valley, Pahalgam', 'Mughal Gardens'],
    itinerary: [
      ['Arrive Srinagar', 'Check in to the houseboat. Evening shikara ride on Dal Lake.'],
      ['Sonmarg', 'Day trip to Sonmarg and the Thajiwas Glacier (ponies extra).'],
      ['Gulmarg', 'Drive to Gulmarg. Gondola ride (tickets extra).'],
      ['Pahalgam', 'Drive via saffron fields and Awantipora ruins to Pahalgam.'],
      ['Pahalgam valleys', 'Betaab Valley, Aru Valley and Chandanwari (local union cabs extra). Back to Srinagar.'],
      ['Departure', 'Nishat and Shalimar Gardens, then drop at Srinagar Airport.']],
    inc: ['One night on a deluxe houseboat', 'One-hour shikara ride']},
  {id: 'jk-honeymoon', state: 'jk', title: 'Kashmir Honeymoon with Houseboat Stay', days: 5, price: 19999,
    themes: ['Honeymoon'], scene: 'lake', img: 'images/jammukashmir.jpg',
    arrive: 'Srinagar Airport', route: 'Srinagar → Gulmarg → Pahalgam',
    highlights: ['Flower decoration on the houseboat', 'Sunset shikara ride', 'Gulmarg meadows', 'Lidder river walks in Pahalgam'],
    itinerary: [
      ['Arrive Srinagar', 'Houseboat check-in and sunset shikara ride.'],
      ['Gulmarg', 'Day trip to Gulmarg.'],
      ['Pahalgam', 'Drive to Pahalgam. Evening by the Lidder river.'],
      ['Pahalgam to Srinagar', 'Betaab Valley, then back to Srinagar for the Mughal Gardens.'],
      ['Departure', 'Drop at Srinagar Airport.']],
    inc: ['Honeymoon decoration on arrival']},
  {id: 'jk-gulmarg', state: 'jk', title: 'Gulmarg Snow Break', days: 3, price: 7499,
    themes: ['Adventure', 'Friends/Group'], scene: 'snow', img: 'images/jammukashmir.jpg',
    arrive: 'Srinagar Airport', route: 'Srinagar → Gulmarg',
    highlights: ['Gulmarg Gondola', 'Skiing taster session (in season)', 'Snow meadows'],
    itinerary: [
      ['Srinagar to Gulmarg', 'Pickup and drive to Gulmarg.'],
      ['Gulmarg', 'Gondola ride and snow activities (charges extra).'],
      ['Departure', 'Drive to Srinagar Airport.']]},
  {id: 'jk-grand', state: 'jk', title: '7 Nights 8 Days Kashmir with Doodhpathri', days: 8, price: 24999, mrp: 28999,
    themes: ['Family', 'Nature'], scene: 'lake', img: 'images/jammukashmir.jpg',
    arrive: 'Srinagar Airport', route: 'Srinagar → Sonmarg → Gulmarg → Doodhpathri → Pahalgam',
    highlights: ['Doodhpathri meadows', 'Two nights in Pahalgam', 'Houseboat night', 'Gulmarg Gondola'],
    itinerary: [
      ['Arrive Srinagar', 'Houseboat and shikara ride.'],
      ['Srinagar', 'Mughal Gardens and Shankaracharya Temple.'],
      ['Sonmarg', 'Day trip to Sonmarg.'],
      ['Gulmarg', 'Drive to Gulmarg and stay overnight.'],
      ['Doodhpathri', 'Day trip to Doodhpathri, back to Srinagar.'],
      ['Pahalgam', 'Drive to Pahalgam.'],
      ['Pahalgam', 'Betaab and Aru valleys.'],
      ['Departure', 'Drive to Srinagar Airport.']]},

  /* ---------- Leh Ladakh ---------- */
  {id: 'la-classic', state: 'la', title: 'Leh, Nubra & Pangong 6 Days', days: 6, price: 24999, mrp: 28999,
    themes: ['Adventure', 'Friends/Group', 'Family'], scene: 'ladakh', img: 'images/lehladakh.jpg',
    arrive: 'Leh Airport', route: 'Leh → Nubra → Pangong → Leh',
    highlights: ['Khardung La', 'Hunder sand dunes and double-humped camels', 'Pangong Tso', 'Thiksey Monastery', 'Magnetic Hill and the Indus–Zanskar confluence'],
    itinerary: [
      ['Arrive Leh', 'Rest all day to adjust to the altitude.'],
      ['Leh local', 'Hall of Fame, Magnetic Hill, Gurudwara Pathar Sahib and the Sangam.'],
      ['Leh to Nubra', 'Over Khardung La to Nubra. Diskit Monastery and Hunder dunes.'],
      ['Nubra to Pangong', 'Drive via Shyok to Pangong Tso.'],
      ['Pangong to Leh', 'Return via Chang La. Thiksey Monastery on the way.'],
      ['Departure', 'Drop at Leh Airport.']],
    prep: ['Leh is above 3,500 m. Do not plan activity on the first day.', 'Permits for Nubra and Pangong are arranged by us; carry photo ID.']},
  {id: 'la-bike', state: 'la', title: 'Ladakh Bike Trip 8 Days', days: 8, price: 32999,
    themes: ['Adventure', 'Friends/Group', 'Solo'], scene: 'ladakh', tm: true, img: 'images/lehladakh.jpg',
    arrive: 'Leh Airport', route: 'Leh → Nubra → Turtuk → Pangong → Leh',
    highlights: ['Royal Enfield 350 for the trip', 'Backup vehicle and mechanic', 'Turtuk village', 'Ride over Khardung La and Chang La'],
    itinerary: [
      ['Arrive Leh', 'Acclimatisation day.'],
      ['Leh local ride', 'Short ride to Shanti Stupa and Leh Palace.'],
      ['Leh to Nubra', 'Ride over Khardung La.'],
      ['Turtuk', 'Ride to Turtuk village near the border.'],
      ['Turtuk to Nubra', 'Return to Hunder.'],
      ['Nubra to Pangong', 'Ride via Shyok to Pangong Tso.'],
      ['Pangong to Leh', 'Ride back over Chang La.'],
      ['Departure', 'Drop at Leh Airport.']],
    inc: ['Royal Enfield bike with fuel', 'Backup vehicle with mechanic'],
    prep: ['A valid two-wheeler driving licence is required.']},
  {id: 'la-short', state: 'la', title: 'Leh Ladakh Short Escape', days: 5, price: 18999,
    themes: ['Family', 'Nature'], scene: 'ladakh', img: 'images/lehladakh.jpg',
    arrive: 'Leh Airport', route: 'Leh → Pangong → Leh',
    highlights: ['Pangong Tso overnight camp', 'Shanti Stupa sunset', 'Hemis and Thiksey monasteries'],
    itinerary: [
      ['Arrive Leh', 'Rest and acclimatise.'],
      ['Leh local', 'Shanti Stupa, Leh Palace and the Sangam.'],
      ['Leh to Pangong', 'Drive over Chang La to Pangong Tso.'],
      ['Pangong to Leh', 'Return via Hemis and Thiksey monasteries.'],
      ['Departure', 'Drop at Leh Airport.']]},

  /* ---------- Rajasthan ---------- */
  {id: 'rj-jaisalmer', state: 'rj', title: '3 Days Jaisalmer Tour with Desert Camp', days: 3, price: 9999,
    themes: ['Friends/Group', 'Adventure', 'Family'], scene: 'desert', img: 'images/rajasthan.jpg',
    arrive: 'Jaisalmer Railway Station / Airport', route: 'Jaisalmer → Sam Dunes',
    highlights: ['Jaisalmer Fort (Sonar Quila)', 'Patwon ki Haveli', 'Camel safari at Sam Sand Dunes', 'Night in a desert camp with folk show'],
    itinerary: [
      ['Arrive Jaisalmer', 'Jaisalmer Fort, Patwon ki Haveli and Gadisar Lake.'],
      ['Sam Sand Dunes', 'Kuldhara village, then camel safari and a night at a desert camp.'],
      ['Departure', 'Morning drive back to Jaisalmer.']]},
  {id: 'rj-udaipur', state: 'rj', title: '5 Days Udaipur Tour with Chittorgarh', days: 5, price: 16999,
    themes: ['Honeymoon', 'Family'], scene: 'palace', img: 'images/rajasthan.jpg',
    arrive: 'Udaipur Airport / Railway Station', route: 'Udaipur → Chittorgarh → Udaipur',
    highlights: ['Boat ride on Lake Pichola', 'City Palace, Udaipur', 'Chittorgarh Fort', 'Sajjangarh Monsoon Palace sunset'],
    itinerary: [
      ['Arrive Udaipur', 'Evening boat ride on Lake Pichola.'],
      ['Udaipur', 'City Palace, Jagdish Temple and Saheliyon ki Bari.'],
      ['Chittorgarh', 'Day trip to Chittorgarh Fort.'],
      ['Udaipur', 'Fateh Sagar Lake and sunset at Sajjangarh.'],
      ['Departure', 'Drop at Udaipur Airport or station.']]},
  {id: 'rj-jodhpur', state: 'rj', title: 'Jodhpur Blue City Tour', days: 5, price: 16500,
    themes: ['Family', 'Solo'], scene: 'desert', img: 'images/rajasthan.jpg',
    arrive: 'Jodhpur Airport / Railway Station', route: 'Jodhpur → Osian → Jodhpur',
    highlights: ['Mehrangarh Fort', 'Jaswant Thada', 'Umaid Bhawan Palace museum', 'Osian temples and dunes'],
    itinerary: [
      ['Arrive Jodhpur', 'Evening at the clock tower market.'],
      ['Jodhpur', 'Mehrangarh Fort and Jaswant Thada.'],
      ['Osian', 'Day trip to the Osian temples and dunes.'],
      ['Jodhpur', 'Umaid Bhawan museum and a blue-city walk.'],
      ['Departure', 'Drop at Jodhpur Airport or station.']]},
  {id: 'rj-royal', state: 'rj', title: 'Royal Rajasthan 9 Days', days: 9, price: 39999, mrp: 46999,
    themes: ['Family', 'Honeymoon'], scene: 'palace', tm: true, img: 'images/rajasthan.jpg',
    arrive: 'Jaipur Airport', route: 'Jaipur → Jodhpur → Jaisalmer → Udaipur',
    highlights: ['Amber Fort and Hawa Mahal', 'Mehrangarh Fort', 'Desert camp at Sam', 'Lake Pichola boat ride', 'Heritage hotels'],
    itinerary: [
      ['Arrive Jaipur', 'Check in to a heritage hotel.'],
      ['Jaipur', 'Amber Fort, Hawa Mahal, City Palace and Jantar Mantar.'],
      ['Jaipur to Jodhpur', 'Drive to Jodhpur.'],
      ['Jodhpur', 'Mehrangarh Fort and Jaswant Thada.'],
      ['Jodhpur to Jaisalmer', 'Drive into the Thar. Evening at Gadisar Lake.'],
      ['Jaisalmer and Sam', 'Jaisalmer Fort, then camel safari and desert camp.'],
      ['Jaisalmer to Udaipur', 'Long drive to Udaipur.'],
      ['Udaipur', 'City Palace and a Lake Pichola boat ride.'],
      ['Departure', 'Drop at Udaipur Airport.']]},

  /* ---------- Uttarakhand ---------- */
  {id: 'uk-nainital', state: 'uk', title: 'Nainital Lake Tour Package', days: 4, price: 9999,
    themes: ['Family', 'Honeymoon'], scene: 'lake', img: 'images/uttarakhand.png',
    arrive: 'Kathgodam Railway Station / Delhi', route: 'Kathgodam → Nainital → Bhimtal',
    highlights: ['Boating on Naini Lake', 'Snow View Point cable car', 'Bhimtal, Sattal and Naukuchiatal', 'Mall Road'],
    itinerary: [
      ['Arrive Nainital', 'Pickup from Kathgodam. Evening on Mall Road.'],
      ['Nainital', 'Naini Lake boating, Naina Devi Temple and the Snow View cable car.'],
      ['Lake tour', 'Bhimtal, Sattal and Naukuchiatal.'],
      ['Departure', 'Drop at Kathgodam.']]},
  {id: 'uk-mussoorie', state: 'uk', title: 'Mussoorie Tour Package from Delhi', days: 3, price: 8999,
    themes: ['Family', 'Friends/Group'], scene: 'hills', img: 'images/uttarakhand.png',
    arrive: 'Delhi / Dehradun', route: 'Delhi → Mussoorie → Delhi',
    highlights: ['Kempty Falls', 'Gun Hill ropeway', 'Lal Tibba viewpoint', 'Mall Road evening'],
    itinerary: [
      ['Delhi to Mussoorie', 'Drive via Dehradun. Evening on Mall Road.'],
      ['Mussoorie', 'Kempty Falls, Gun Hill ropeway and Lal Tibba.'],
      ['Return to Delhi', 'Drive back to Delhi.']]},
  {id: 'uk-rishikesh', state: 'uk', title: 'Haridwar & Rishikesh Spiritual Tour', days: 4, price: 10999, mrp: 12999,
    themes: ['Solo', 'Family', 'Adventure'], scene: 'river', img: 'images/uttarakhand.png',
    arrive: 'Delhi / Haridwar Railway Station', route: 'Haridwar → Rishikesh',
    highlights: ['Ganga Aarti at Har Ki Pauri', 'Evening aarti at Triveni Ghat', 'River rafting from Shivpuri', 'Ram Jhula and the Beatles Ashram'],
    itinerary: [
      ['Arrive Haridwar', 'Evening Ganga Aarti at Har Ki Pauri.'],
      ['Haridwar to Rishikesh', 'Mansa Devi ropeway, then drive to Rishikesh.'],
      ['Rishikesh', 'Rafting from Shivpuri (extra), Ram Jhula, Beatles Ashram and Triveni Ghat aarti.'],
      ['Departure', 'Drop at Haridwar or Dehradun.']]},
  {id: 'uk-grand', state: 'uk', title: 'Uttarakhand Tour Package from Delhi', days: 5, price: 17999,
    themes: ['Family', 'Nature', 'Friends/Group'], scene: 'river', img: 'images/uttarakhand.png',
    arrive: 'Delhi', route: 'Delhi → Rishikesh → Mussoorie → Delhi',
    highlights: ['Rishikesh Ganga Aarti', 'Mussoorie Mall Road', 'Kempty Falls', 'Dehradun Robber\'s Cave'],
    itinerary: [
      ['Delhi to Rishikesh', 'Drive to Rishikesh. Evening aarti.'],
      ['Rishikesh', 'Ram Jhula and rafting (optional).'],
      ['Rishikesh to Mussoorie', 'Robber\'s Cave in Dehradun on the way.'],
      ['Mussoorie', 'Kempty Falls and Gun Hill.'],
      ['Return to Delhi', 'Drive back to Delhi.']]},

  /* ---------- Delhi & Agra ---------- */
  {id: 'dl-delhi-agra', state: 'dl', title: '3 Days Delhi Agra Tour Package – Delhi Sightseeing & Taj Mahal Tour', days: 3, price: 7800, mrp: 10000,
    themes: ['Family', 'Honeymoon'], scene: 'city', tm: true, img: 'images/delhiagra.jpg',
    arrive: 'Delhi Railway Station / Airport', route: 'Delhi → Agra → Delhi',
    highlights: ['Delhi local sightseeing covering major historical landmarks', 'Visit the magnificent Qutub Minar and Humayun\'s Tomb', 'Explore the peaceful Lotus Temple', 'Photo stop at India Gate and Rashtrapati Bhavan', 'Visit the historic Red Fort', 'Enjoy shopping and leisure time at Connaught Place', 'Comfortable road journey from Delhi to Agra', 'Explore the grand Agra Fort', 'Visit the world-famous Taj Mahal', 'Convenient Delhi Railway Station/Airport pickup and drop'],
    itinerary: [
      ['Delhi Arrival & Sightseeing', 'Pickup from the station or airport. Qutub Minar, Humayun\'s Tomb, Lotus Temple, India Gate and Rashtrapati Bhavan. Evening at Connaught Place.'],
      ['Delhi to Agra & Agra Sightseeing', 'Red Fort photo stop, then drive to Agra. Agra Fort and the Taj Mahal.'],
      ['Agra to Delhi & Departure', 'Sunrise at the Taj (optional), drive back to Delhi for your drop.']],
    inc: ['Overnight stay in Delhi', 'Overnight stay in Agra']},
  {id: 'dl-golden', state: 'dl', title: 'Golden Triangle 6 Days – Delhi, Agra & Jaipur', days: 6, price: 19999, mrp: 23999,
    themes: ['Family', 'Solo'], scene: 'city', img: 'images/delhiagra.jpg',
    arrive: 'Delhi Airport', route: 'Delhi → Agra → Jaipur → Delhi',
    highlights: ['Taj Mahal at sunrise', 'Fatehpur Sikri', 'Amber Fort, Jaipur', 'Old Delhi rickshaw ride'],
    itinerary: [
      ['Arrive Delhi', 'Check in. Evening at India Gate.'],
      ['Delhi', 'Old Delhi rickshaw ride, Red Fort, Qutub Minar and Humayun\'s Tomb.'],
      ['Delhi to Agra', 'Drive to Agra. Agra Fort and Mehtab Bagh sunset.'],
      ['Agra to Jaipur', 'Sunrise at the Taj, Fatehpur Sikri on the way to Jaipur.'],
      ['Jaipur', 'Amber Fort, Hawa Mahal, City Palace and Jantar Mantar.'],
      ['Jaipur to Delhi', 'Drive back to Delhi for your drop.']]},

  /* ---------- Bhutan ---------- */
  {id: 'bt-classic', state: 'bt', title: 'Bhutan 6 Days – Thimphu, Punakha & Paro', days: 6, price: 34999, mrp: 39999,
    themes: ['Family', 'Honeymoon', 'Nature'], scene: 'monastery', tm: true, img: 'images/bhutan.jpg',
    arrive: 'Bagdogra Airport', route: 'Bagdogra → Phuentsholing → Thimphu → Punakha → Paro',
    highlights: ['Tiger\'s Nest (Taktsang) hike', 'Punakha Dzong and suspension bridge', 'Dochula Pass and its 108 chortens', 'Buddha Dordenma, Thimphu'],
    itinerary: [
      ['Bagdogra to Phuentsholing', 'Drive to the border town of Phuentsholing. Entry permit formalities.'],
      ['Phuentsholing to Thimphu', 'Drive up to Thimphu.'],
      ['Thimphu to Punakha', 'Dochula Pass, Punakha Dzong and the suspension bridge.'],
      ['Punakha to Paro', 'Drive to Paro. Rinpung Dzong.'],
      ['Tiger\'s Nest', 'Hike to Taktsang Monastery.'],
      ['Departure', 'Drop at Paro Airport.']],
    exc: ['Bhutan Sustainable Development Fee (SDF), charged per night by the Government of Bhutan'],
    prep: ['Indian citizens need a valid passport or voter ID card to enter Bhutan.']},
  {id: 'bt-short', state: 'bt', title: 'Paro & Thimphu 5 Days', days: 5, price: 29999,
    themes: ['Solo', 'Honeymoon'], scene: 'monastery', img: 'images/bhutan.jpg',
    arrive: 'Paro Airport', route: 'Paro → Thimphu → Paro',
    highlights: ['Tiger\'s Nest hike', 'Chele La Pass', 'Memorial Chorten and Tashichho Dzong', 'Traditional Bhutanese dinner'],
    itinerary: [
      ['Arrive Paro, drive to Thimphu', 'Drive to Thimphu. Evening at the Memorial Chorten.'],
      ['Thimphu', 'Buddha Dordenma, Tashichho Dzong and the Takin Preserve.'],
      ['Thimphu to Paro', 'Chele La Pass on the way to Paro.'],
      ['Tiger\'s Nest', 'Hike to Taktsang Monastery.'],
      ['Departure', 'Drop at Paro Airport.']],
    exc: ['Bhutan Sustainable Development Fee (SDF), charged per night by the Government of Bhutan'],
    prep: ['Indian citizens need a valid passport or voter ID card to enter Bhutan.']},

  /* ---------- Thailand ---------- */
  {id: 'th-bkk-pattaya', state: 'th', title: '5 Days Pattaya Bangkok Tour Package', days: 5, price: 23500, mrp: 27999,
    themes: ['Friends/Group', 'Honeymoon', 'Family'], scene: 'pagoda', img: 'images/thailand.jpg',
    arrive: 'Bangkok Suvarnabhumi Airport', route: 'Bangkok → Pattaya → Bangkok',
    highlights: ['Coral Island speedboat trip', 'Alcazar show, Pattaya', 'Grand Palace and Wat Arun', 'Safari World and Marine Park'],
    itinerary: [
      ['Arrive Bangkok, transfer to Pattaya', 'Transfer to Pattaya. Evening Alcazar show.'],
      ['Coral Island', 'Speedboat to Coral Island (Koh Larn).'],
      ['Pattaya to Bangkok', 'Transfer to Bangkok. Evening Chao Phraya cruise (optional).'],
      ['Bangkok', 'Grand Palace, Wat Arun and Safari World.'],
      ['Departure', 'Drop at Suvarnabhumi Airport.']],
    exc: ['Thailand visa or visa-on-arrival fees, if applicable'],
    prep: ['Your passport must be valid for at least six months from arrival.', 'Check current visa rules for Indian passport holders before booking.']},
  {id: 'th-phuket-krabi', state: 'th', title: 'Phuket & Krabi Island Holiday', days: 6, price: 34999,
    themes: ['Honeymoon', 'Adventure'], scene: 'beach', img: 'images/thailand.jpg',
    arrive: 'Phuket Airport', route: 'Phuket → Krabi',
    highlights: ['Phi Phi Islands day trip', 'Phang Nga Bay and James Bond Island', 'Krabi 4-island tour', 'Railay Beach'],
    itinerary: [
      ['Arrive Phuket', 'Check in. Evening at Patong.'],
      ['Phi Phi Islands', 'Full-day boat trip to the Phi Phi Islands.'],
      ['Phang Nga Bay', 'Sea caves and James Bond Island.'],
      ['Phuket to Krabi', 'Transfer to Krabi. Evening at Ao Nang.'],
      ['Krabi 4 islands', 'Longtail boat island hopping and Railay Beach.'],
      ['Departure', 'Drop at Krabi Airport.']],
    exc: ['Thailand visa or visa-on-arrival fees, if applicable', 'National park fees on island tours'],
    prep: ['Your passport must be valid for at least six months from arrival.', 'Check current visa rules for Indian passport holders before booking.']}
];
